# Generated by Django 3.0.3 on 2020-08-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
                ('Email', models.EmailField(max_length=256)),
                ('Mobile', models.IntegerField()),
            ],
        ),
    ]
